### ISSUE TITLE
How can I get the Repaired pictures？

### ISSUE THREAD

**Issue by WujiangXu** [xiaoyu258/GeoProj#2]
I use the resampling.py，but I find I don't have the flow.npy file.
I read the map file and save the file as npy.Then try to use it in this resampling.py file but it comes to some errors.
`  File "resampling.py", line 203, in <module>
    resImg, resMsk = rectification(distortedImg, flow)
  File "resampling.py", line 169, in rectification
    padu[0:H, 0:W] = flow[0][0:H, 0:W]
IndexError: too many indices for array`

I don't know how to deal with it.Can you tell me how to fix that error.Thank you.

**Comment by cupcakefromchina** [comment]
Can you tell me that how you save the data about the flow_output.data.
I save it use the below code,but it can't use the .npy file in the resampling.py.
`np.transpose(u+v)
np.save`

**Comment by sanahtech** [comment]
please share the solution of above problem
